# 让 Makedown 文档支持 HTML 语法，高亮，文章目录等功能
[goldmark]
renderer.unsafe = true

[highlight]
anchorLineNos = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
noClasses = false

[tableOfContents]
startLevel = 2
endLevel = 4
