[[main]]
identifier = "home"
name = "首页"
pageRef = "/"
pre = "home"
weight = 1

[[main]]
identifier = "about"
name = "关于"
pageRef = "/about"
pre = "user"
weight = 2

[[main]]
identifier = "flinks"
name = "友情链接"
pageRef = "/flinks"
pre = "thumbs-up"
weight = 3

[[main]]
identifier = "archives"
name = "归档"
pageRef = "/archives"
pre = "archive"
weight = 5

[[main]]
identifier = "commonweal"
name = "公益 404"
pageRef = "/404.html"
pre = "heartbeat"
weight = 6
