[[main]]
identifier = "home"
name = "Home"
pageRef = "/"
pre = "home"
weight = 1

[[main]]
identifier = "about"
name = "About"
pageRef = "/about.html"
pre = "user"
weight = 2

[[main]]
identifier = "flinks"
name = "Friend's Links"
pageRef = "/flinks.html"
pre = "thumbs-up"
weight = 3

[[main]]
identifier = "archives"
name = "Archives"
pageRef = "/archives"
pre = "archive"
weight = 5

[[main]]
identifier = "commonweal"
name = "Commonweal404"
pageRef = "/404.html"
pre = "heartbeat"
weight = 6
