name: check & deploy

on:
  push:
    branches: [ resource ]
  pull_request:
    branches: [ resource ]

env:
  TZ: Asia/Shanghai

jobs:
  check-build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get codes
      uses: actions/checkout@v2

    - name: Use Node.js v12.18.2
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.2

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Check varsion
      run: |
        echo node version: $(node -v)
        echo npm version: $(npm -v)

    - name: Install dependencies
      run: |
        npm install hexo-cli -g
        npm install

    - name: Update submodule
      run: |
        git submodule init
        git submodule update

    - name: Deploy
      env:
        SSH_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

        git config --global user.name 'GitAction'
        git config --global user.email 'action@github.com'

        hexo clean
        hexo generate
        hexo deploy
