name: check & deploy

on:
  push:
    branches: [ resource ]
  pull_request:
    branches: [ resource ]

jobs:
  check build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js v12.16.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
    - run: node -v
    - run: npm -v

    # - name: Hexo Action
    #   uses: sma11black/hexo-action@v1.0.1
    #     with: 
